#!/usr/bin/env python3
"""Deliver the daily report to Telegram and email.

`hunter.py report` prints to stdout, which is useless on a schedule. This module is the
delivery layer, and it makes one deliberate routing decision:

  * A report with real candidates goes to BOTH Telegram (instant, phone-native, the
    right channel for "visit today") and email (forwardable, renders the full detail).
  * A "NO CHANGE" report goes to email ONLY. Telegram stays silent.

That asymmetry is the whole point. A radar that pings your phone every single day gets
muted inside a week, and a muted radar is worse than no radar because it looks like it
is working. The daily email remains the proof-of-life that the job actually ran.

Credentials come from the environment, never from a file in the repo:
  TELEGRAM_BOT_TOKEN, TELEGRAM_CHAT_ID
  SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASSWORD, EMAIL_FROM, EMAIL_TO
A channel with missing credentials is skipped with a warning, not a crash: losing the
email must never suppress an urgent Telegram alert.
"""

from __future__ import annotations

import argparse
import json
import os
import smtplib
import sys
import urllib.error
import urllib.parse
import urllib.request
from email.message import EmailMessage
from html import escape
from pathlib import Path
from typing import Optional

import hunter
from hunter import HunterError, local_now

ROOT = Path(__file__).resolve().parent
NO_CHANGE = "NO CHANGE — nothing worth visiting today."
TELEGRAM_LIMIT = 3900  # Telegram hard-caps at 4096; leave room for the chunk counter.


def telegram_chunks(text: str, limit: int = TELEGRAM_LIMIT) -> list[str]:
    """Split on candidate boundaries so a single property is never cut in half."""
    blocks = text.split("\n\n")
    chunks: list[str] = []
    current = ""
    for block in blocks:
        candidate = f"{current}\n\n{block}" if current else block
        if len(candidate) <= limit:
            current = candidate
            continue
        if current:
            chunks.append(current)
        # A single block longer than the limit still has to be broken somewhere.
        while len(block) > limit:
            chunks.append(block[:limit])
            block = block[limit:]
        current = block
    if current:
        chunks.append(current)
    return chunks or [text[:limit]]


def send_telegram(text: str, dry_run: bool) -> dict[str, object]:
    token = os.environ.get("TELEGRAM_BOT_TOKEN")
    chat_id = os.environ.get("TELEGRAM_CHAT_ID")
    if not token or not chat_id:
        return {"channel": "telegram", "sent": False, "reason": "TELEGRAM_BOT_TOKEN/TELEGRAM_CHAT_ID not set"}
    chunks = telegram_chunks(text)
    if dry_run:
        return {"channel": "telegram", "sent": False, "reason": "dry-run", "chunks": len(chunks)}
    url = f"https://api.telegram.org/bot{token}/sendMessage"
    for index, chunk in enumerate(chunks, start=1):
        prefix = f"({index}/{len(chunks)})\n" if len(chunks) > 1 else ""
        body = urllib.parse.urlencode(
            {
                "chat_id": chat_id,
                "text": prefix + chunk,
                "disable_web_page_preview": "false",
            }
        ).encode("utf-8")
        request = urllib.request.Request(url, data=body, method="POST")
        try:
            with urllib.request.urlopen(request, timeout=30) as response:
                payload = json.loads(response.read().decode("utf-8"))
        except urllib.error.HTTPError as exc:
            detail = exc.read().decode("utf-8", "replace")[:300]
            raise HunterError(f"Telegram rejected the message ({exc.code}): {detail}") from exc
        except urllib.error.URLError as exc:
            raise HunterError(f"Could not reach Telegram: {exc.reason}") from exc
        if not payload.get("ok"):
            raise HunterError(f"Telegram reported failure: {payload}")
    return {"channel": "telegram", "sent": True, "chunks": len(chunks)}


def html_body(text: str, subject: str) -> str:
    """Minimal readable HTML. Alert bodies are plain text by design, so we preserve
    their line structure and only linkify nothing -- mail clients autolink URLs."""
    escaped = escape(text).replace("\n", "<br>")
    return (
        '<html><body style="font-family:-apple-system,BlinkMacSystemFont,\'SF Pro Text\','
        "Helvetica,Arial,sans-serif;font-size:15px;line-height:1.55;color:#1d1d1f;"
        'max-width:680px;margin:0 auto;padding:20px">'
        f'<h2 style="font-size:17px;margin:0 0 16px">{escape(subject)}</h2>'
        f'<div style="white-space:normal">{escaped}</div>'
        '<hr style="border:none;border-top:1px solid #d2d2d7;margin:24px 0 12px">'
        '<p style="font-size:12px;color:#6e6e73;margin:0">'
        "Generated by san-isidro-house-hunter. Every figure above traces to the linked "
        "original listing; anything unconfirmed is marked <em>Not verified.</em>"
        "</p></body></html>"
    )


def send_email(text: str, subject: str, dry_run: bool) -> dict[str, object]:
    host = os.environ.get("SMTP_HOST")
    port = int(os.environ.get("SMTP_PORT", "465"))
    user = os.environ.get("SMTP_USER")
    password = os.environ.get("SMTP_PASSWORD")
    sender = os.environ.get("EMAIL_FROM") or user
    recipients = [item.strip() for item in (os.environ.get("EMAIL_TO") or "").split(",") if item.strip()]
    if not host or not user or not password or not sender or not recipients:
        return {"channel": "email", "sent": False, "reason": "SMTP_HOST/SMTP_USER/SMTP_PASSWORD/EMAIL_TO not set"}
    if dry_run:
        return {"channel": "email", "sent": False, "reason": "dry-run", "recipients": len(recipients)}
    message = EmailMessage()
    message["Subject"] = subject
    message["From"] = sender
    message["To"] = ", ".join(recipients)
    message.set_content(text)
    message.add_alternative(html_body(text, subject), subtype="html")
    try:
        if port == 587:
            with smtplib.SMTP(host, port, timeout=45) as server:
                server.starttls()
                server.login(user, password)
                server.send_message(message)
        else:
            with smtplib.SMTP_SSL(host, port, timeout=45) as server:
                server.login(user, password)
                server.send_message(message)
    except (smtplib.SMTPException, OSError) as exc:
        raise HunterError(f"Email delivery failed via {host}:{port}: {exc}") from exc
    return {"channel": "email", "sent": True, "recipients": len(recipients)}


def is_no_change(text: str) -> bool:
    return text.strip() == NO_CHANGE


def subject_for(text: str) -> str:
    today = local_now().date().isoformat()
    if is_no_change(text):
        return f"San Isidro radar {today}: sin novedades"
    if "🚨 ACT NOW" in text:
        return f"🚨 San Isidro radar {today}: ACT NOW"
    count = sum(text.count(marker) for marker in ("🚨 ACT NOW", "🟣 PRE-MARKET", "🟡 INVESTIGAR", "⚡ VER HOY"))
    return f"San Isidro radar {today}: {count} candidato(s)"


def deliver(text: str, dry_run: bool, force_telegram: bool = False) -> list[dict[str, object]]:
    subject = subject_for(text)
    results: list[dict[str, object]] = []
    errors: list[str] = []

    if is_no_change(text) and not force_telegram:
        results.append({"channel": "telegram", "sent": False, "reason": "suppressed: NO CHANGE"})
    else:
        try:
            results.append(send_telegram(text, dry_run))
        except HunterError as exc:
            errors.append(str(exc))
            results.append({"channel": "telegram", "sent": False, "reason": str(exc)})

    try:
        results.append(send_email(text, subject, dry_run))
    except HunterError as exc:
        errors.append(str(exc))
        results.append({"channel": "email", "sent": False, "reason": str(exc)})

    # Report every failure, but only after both channels have been attempted.
    if errors and not any(result.get("sent") for result in results):
        raise HunterError("all delivery channels failed: " + " | ".join(errors))
    for error in errors:
        print(f"warning: {error}", file=sys.stderr)
    return results


def load_text(args: argparse.Namespace) -> str:
    if args.text is not None:
        return args.text
    if args.stdin:
        return sys.stdin.read()
    config = hunter.read_config(Path(args.config))
    with hunter.connect(Path(args.database)) as conn:
        hunter.initialise(conn)
        return hunter.report(conn, config, args.since)


def main(argv: Optional[list[str]] = None) -> int:
    base = argparse.ArgumentParser(description="Deliver the San Isidro radar report to Telegram and email")
    base.add_argument("--database", default=str(hunter.DEFAULT_DATABASE))
    base.add_argument("--config", default=str(hunter.DEFAULT_CONFIG))
    base.add_argument("--since", help="inclusive ISO date; defaults to today in Argentina")
    base.add_argument("--stdin", action="store_true", help="read the report from stdin")
    base.add_argument("--text", help="deliver this literal text (for testing credentials)")
    base.add_argument("--dry-run", action="store_true", help="resolve routing without sending")
    base.add_argument("--force-telegram", action="store_true", help="send to Telegram even on NO CHANGE")
    base.add_argument("--save", help="also write the delivered report to this path")
    args = base.parse_args(argv)
    try:
        text = load_text(args)
        if args.save:
            path = Path(args.save)
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text + "\n", encoding="utf-8")
        results = deliver(text, args.dry_run, args.force_telegram)
    except HunterError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2
    print(json.dumps({"subject": subject_for(text), "no_change": is_no_change(text), "delivery": results}, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
